apiVersion: v1
kind: ConfigMap
metadata:
  name: konnectivity-proxy
data:
  haproxy.cfg: |
    defaults
      mode http
      timeout connect 5s
      timeout client 30s
      timeout server 30s
    frontend http-in
      bind *:10080
      default_backend be
    backend be
      mode http
      server ks konnectivity-server:8090 ssl verify required ca-file /etc/secret/ca.crt crt /etc/secret/konnectivity-proxy-combined.pem
